[panel]
title = "Physique-Chimie - Documents"
description = "Ressources pédagogiques"

[marketplace]
enabled = false
psk = "password123"
level = 1

[seo]
enabled = false
domain = "https://physique-chimie-docs.vercel.app"

[db]
name = "database"
username = "user"
password = "password"
postgres = false

[postgres]
domain = ""
port = 5432

[server.server]
port = 3000
wisp = true
logging = false

[masqr]
enabled = false
failed = "failed.html"
whitelisted = []
url = ""

[proxy]
url = "https://www.google.com"
